# 作成したいコンテナを列挙する
services:
  db:
    # DBコンテナを作成するために利用するイメージ
    image: mysql:8.0
    # データの保存先 (ホストディレクトリ：コンテナ内ディレクトリ）
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      # MySQL8.0　必須
      MYSQL_ROOT_PASSWORD: password
    # 公開するポート番号
    ports:
      - 3306:3306
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/rails-graphql
    depends_on:
      - db
      - redis
  web:
    # . を指定することで、docker-compose.ymlと同じ場所にDockerfileがあることを示している
    build: .
    # コンテナ起動時に実行されるコマンド
    # すでに rails serverが動いている場合は停止、その後に起動している
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"
    # データの保存先 (ホストディレクトリ：コンテナ内ディレクトリ）
    volumes:
      - .:/rails-graphql
    # 公開するポート番号
    ports:
      - '3000:3000'
    # コンテナの作成順序。MySQLコンテナが起動してからRailsのコンテナを起動する
    depends_on:
      - db
      - redis
# ホストディレクトリの指定
volumes:
  mysql_data:
  redis_data:
